(*) ->[$(document).ready] "Setup jQuery-UI"
--> "Load Playlist"
--> if "Playlist Successful" then
  -->[y] "Parse Playlist"
  --> "Create Playlist"
else
  -->[n] "Parse Default Playlist"
  --> "Create Playlist"
endif 
"Create Playlist" --> ===B2===
--> "Load API"
"Load API" -->[onYouTubeIframeAPIReady] "new YT.Player"
--> ===B1===
-->[onPlayerReady] startProgressUpdate
--> (*)
===B1=== -->[onPlayerStateChange] "Update Controls"
===B2=== -->[Select item] "Play new item"